# Pages CMS Configuration
# Documentation: https://pagescms.org/docs/configuration/

# Media configuration
media: src/assets

# Reusable components
components:
  # Button component
  button:
    type: object
    fields:
      - name: variant
        label: Variant
        type: select
        options:
          values:
            - label: Primary
              value: primary
            - label: Secondary
              value: secondary
        required: true
        default: primary
      - name: size
        label: Size
        type: select
        options:
          values:
            - label: Small
              value: sm
            - label: Medium
              value: md
            - label: Large
              value: lg
        required: true
        default: md
      - name: text
        label: Text
        type: string
        required: true
        description: The text displayed on the button
      - name: href
        label: Link URL
        type: string
        required: true
        description: The URL this button links to

  # Card component
  card:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: content
        label: Content
        type: rich-text
        description: Brief description of the card
      - name: image
        label: Image
        type: image
        description: Card image (absolute path, e.g. /src/assets/images/card.jpg)
      - name: button
        label: Button
        component: button

  # Person component
  person:
    type: object
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: Unique identifier (slug format, e.g. john-doe)
      - name: name
        label: Name
        type: string
        required: true
      - name: headshot
        label: Headshot
        type: image
        required: true
        description: Absolute path from root (e.g. /src/assets/people/john-doe.png)
      - name: title
        label: Job Title
        type: string
        required: true
      - name: sections
        label: Sections
        type: string
        list: true
        description: Department/section tags (e.g. Leadership, Engineering)

  # Partner component
  partner:
    type: object
    fields:
      - name: name
        label: Name
        type: string
        required: true
      - name: affiliation
        label: Affiliation
        type: string
        description: e.g. "Platinum Sponsor"
      - name: url
        label: Website URL
        type: string
        description: Partner's website
      - name: category
        label: Category
        type: string
        required: true
        description: e.g. sponsor, infrastructure, community
      - name: image
        label: Logo
        type: image
        required: true
        description: Absolute path to partner logo (e.g. /src/assets/partners/logo.png)

  # Section component (for nested flexi sections)
  section:
    type: block
    blockKey: type
    description: Add and arrange page sections in any order
    blocks:
      - name: richText
        label: Rich Text Section
        component: richtext_section
      
      - name: button
        label: Button Section
        component: button_section

      - name: card
        label: Card Section
        component: card_section
  
  background_select:
    type: object
    fields:
      - name: bgColor
        label: Color
        type: select
        options:
          values:
            - label: White
              value: white
            - label: Gray
              value: gray
            - label: Gradient
              value: gradient
        default: white
        description: Select a section background for this section
      - name: bgType
        label: Type
        type: select
        options:
          values:
            - label: Full-width
              value: full
            - label: Contained
              value: contained
        default: full
        description: Select the background type for this section
      

  # Section components for block variants
  hero_section:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: subtitle
        label: Subtitle
        type: string
      - name: backgroundImage
        label: Background Image
        type: image
        description: Optional hero background image (absolute path, e.g. /src/assets/hero-bg.jpg)

  richtext_section:
    type: object
    fields:
      - name: background
        label: Section Background
        component: background_select
      - name: content
        label: Content
        type: rich-text
        required: true
        description: Markdown content for this section

  button_section:
    type: object
    fields:
      - name: background
        label: Section Background
        component: background_select
      - name: title
        label: Title (Optional)
        type: string
        required: false
      - name: buttons
        label: Buttons
        type: object
        list: true
        component: button
        description: Buttons

  card_section:
    type: object
    fields:
      - name: background
        label: Section Background
        component: background_select
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: rich-text
      - name: cards
        label: Cards
        type: object
        list: true
        component: card
        description: Grid of content cards
      - name: buttons
        label: Action Buttons
        type: object
        list: true
        component: button
        description: Buttons at the bottom of the section

  flexi_section:
    type: object
    fields:
      - name: background
        label: Section Background
        component: background_select
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: rich-text
      - name: sections
        label: Sections
        type: object
        list: true
        component: section
        description: Nested sections within this flexi section

  people_section:
    type: object
    fields:
      - name: background
        label: Section Background
        component: background_select
      - name: category
        label: Category
        type: string
        description: Filter people by section/department (e.g. "Engineering", "Leadership"). Leave empty to show all people.

  partners_section:
    type: object
    fields:
      - name: background
        label: Section Background
        component: background_select
      - name: title
        label: Title
        type: string
        required: true
      - name: category
        label: Category
        type: string
        description: Filter partners by category (e.g. "sponsor", "technology"). Leave empty to show all partners.

  # Homepage-specific sections
  homepage_hero_section:
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: backgroundImage
        label: Background Image
        type: image
      - name: stats
        label: Stats
        type: object
        list: true
        fields:
          - name: label
            label: Label
            type: string
            required: true
          - name: value
            label: Value
            type: string
            required: true
        description: Key statistics to display in the hero section

# Content collections
content:
  # Pages collection
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    format: yaml
    filename: '{fields.permalink}.yaml'
    view:
      fields: [title, description]
      primary: title
    fields:
      - name: title
        label: Page Title
        type: string
        required: true
        description: The title of the page

      - name: permalink
        label: Permalink
        type: string
        description: The slug, without slashes or parents, like 'about-us' or 'omg-3'.
        pattern:
          {
            message: "This must be a web-safe string like 'about-us' or 'omg-3'.",
            regex: '^[a-zA-Z0-9_-]*$',
          }
        required: true

      - name: description
        label: Page Description
        type: rich-text
        description: SEO meta description

      - name: sections
        label: Page Sections
        type: block
        list: true
        required: true
        blockKey: type
        description: Add and arrange page sections in any order
        blocks: &page_section_blocks
          - name: hero
            label: Hero Section
            component: hero_section

          - name: richText
            label: Rich Text Section
            component: richtext_section
          
          - name: button
            label: Button Section
            component: button_section

          - name: card
            label: Card Section
            component: card_section

          - name: people
            label: People Section
            component: people_section

          - name: partners
            label: Partners Section
            component: partners_section
          
          - name: flexi
            label: Flexi Section
            component: flexi_section

  # Homepage collection (extends pages)
  - name: homepage
    label: Homepage
    type: file
    path: src/content/homepage/index.yaml
    fields:
      - name: sections
        label: Page Sections
        type: block
        list: true
        required: true
        blockKey: type
        description: Add and arrange page sections in any order
        blocks:
          # *page_section_blocks
          - name: homepage_hero
            label: Hero Section
            component: homepage_hero_section
          # Add homepage-specific blocks below:
          # - name: customHomepageSection
          #   label: Custom Homepage Section
          #   component: custom_homepage_section

  # People collection
  - name: people
    label: People
    type: collection
    path: src/content/people
    format: json
    filename: '{{fields.id}}.json'
    view:
      fields: [name, title]
      primary: name
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: Unique identifier (slug format, e.g. john-doe)

      - name: name
        label: Name
        type: string
        required: true

      - name: headshot
        label: Headshot
        type: image
        required: true
        description: Absolute path from root (e.g. /src/assets/people/john-doe.png)

      - name: title
        label: Job Title
        type: string
        required: true

      - name: sections
        label: Sections/Departments
        type: string
        list: true
        description: Tags like "Leadership", "Engineering", etc. Must match categories defined in Categories > people

  # Partners collection
  - name: partners
    label: Partners
    type: collection
    path: src/content/partners
    format: json
    filename: '{{fields.id}}.json'
    view:
      fields: [name, category, affiliation]
      primary: name
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: Unique identifier (slug format, e.g. tech-corp)

      - name: name
        label: Partner Name
        type: string
        required: true

      - name: affiliation
        label: Affiliation
        type: string
        description: e.g. "Platinum Sponsor", "Technology Partner"

      - name: url
        label: Website URL
        type: string
        description: Partner's website URL

      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - label: Sponsor
              value: sponsor
            - label: Infrastructure
              value: infrastructure
            - label: Community
              value: community
            - label: Technology
              value: technology
            - label: Media
              value: media
        description: Partner category for filtering. Must match categories defined in Categories > partners

      - name: image
        label: Logo
        type: image
        description: Absolute path to partner logo (e.g. /src/assets/partners/logo.png)

      - name: order
        label: Display Order
        type: number
        default: 999
        description: Lower numbers appear first (1, 2, 3...)

  # Categories collection
  - name: categories
    label: Categories
    type: collection
    path: src/content/categories
    format: json
    filename: '{{fields.id}}.json'
    view:
      fields: [name, id]
      primary: name
    fields:
      - name: id
        label: ID
        type: string
        required: true
        description: Unique identifier (e.g. people, partners, blog)

      - name: name
        label: Name
        type: string
        required: true
        description: Display name for this category group

      - name: categories
        label: Categories
        type: string
        list: true
        required: true

  # Site configuration (singleton)
  - name: site-config
    label: Site Settings
    type: file
    path: src/content/site/config.json
    fields:
      - name: title
        label: Site Title
        type: string
        required: true
        description: The name of your website

      - name: description
        label: Site Description
        type: string
        required: true
        description: Default meta description for SEO

      - name: url
        label: Site URL
        type: string
        required: true
        description: Your website's URL (e.g. https://example.com)

      - name: favicon
        label: Favicon Path
        type: string
        default: /favicon.svg
        description: Path to your favicon file

      - name: defaultOgImage
        label: Default Open Graph Image
        type: image
        description: Default image for social media sharing

      - name: social
        label: Social Media Links
        type: object
        fields:
          - name: bluesky
            label: BlueSky URL
            type: string
            description: Full URL to your Bluesky profile
          - name: mastodon
            label: Mastodon URL
            type: string
            description: Full URL to your Mastodon profile

          - name: github
            label: GitHub URL
            type: string
            description: Full URL to your GitHub profile or organization

          - name: linkedin
            label: LinkedIn URL
            type: string
            description: Full URL to your LinkedIn profile or company page

          - name: x
            label: X URL
            type: string
            description: Full URL to your X profile

          - name: facebook
            label: Facebook URL
            type: string
            description: Full URL to your Facebook page

          - name: instagram
            label: Instagram URL
            type: string
            description: Full URL to your Instagram profile

          - name: youtube
            label: YouTube URL
            type: string
            description: Full URL to your YouTube channel

  # Navigation menus
  - name: navigation
    label: Navigation Menus
    type: collection
    path: src/content/navigation
    format: json
    filename: '{{fields.slug}}'
    view:
      fields: [title]
      primary: title
    fields:
      - name: slug
        label: Menu ID
        type: string
        required: true
        description: Unique identifier for this menu (e.g. main, footer-1, footer-2)
        pattern:
          {
            message: "Must be a web-safe string like 'main' or 'footer-1'.",
            regex: '^[a-zA-Z0-9_-]*$',
          }

      - name: title
        label: Menu Title
        type: string
        required: true
        description: Display title for this menu

      - name: items
        label: Menu Items
        type: object
        list: true
        required: true
        fields:
          - name: label
            label: Link Label
            type: string
            required: true
            description: Text displayed for the link

          - name: href
            label: URL
            type: string
            required: true
            description: Link destination (e.g. / or /about)

          - name: description
            label: Description
            type: string
            description: Optional description for accessibility

  # Blog collection
  - name: blog
    label: Blog
    type: collection
    path: src/content/blog
    filename: '{{fields.permalink}}.md'
    view:
      fields: [heroImage, title, publishedDate, published]
      primary: title
    fields:
      - name: permalink
        label: Permalink
        type: string
        required: true
        description: URL-friendly identifier (e.g. my-blog-post-title)
        pattern:
          {
            message: "Must be a web-safe string like 'my-blog-post-title'.",
            regex: '^[a-zA-Z0-9_-]*$',
          }

      - name: title
        label: Title
        type: string
        required: true
        description: Blog post title

      - name: excerpt
        label: Excerpt
        type: string
        description: Short summary of the blog post

      - name: authors
        label: Authors
        type: reference
        options:
          collection: people
          multiple: true
          value: "{id}"
          label: "{fields.name}"

      - name: published
        label: Status
        type: select
        required: true
        default: draft
        options:
          values:
            - label: Draft
              value: draft
            - label: Published
              value: published

      - name: tags
        label: Tags
        type: string
        list: true
        required: true
        description: Blog post tags/categories. Must match categories defined in Categories > blog

      - name: publishedDate
        label: Published Date
        type: date
        options:
          format: yyyy-MM-dd
        required: true
        description: Date the blog post was published

      - name: heroImage
        label: Hero Image
        type: image
        description: Featured image for the blog post

      - name: relatedPosts
        label: Related Posts
        type: reference
        description: Select up to 3 related blog posts
        options:
          collection: blog
          multiple: true
          value: "{permalink}"
          label: "{title}"
          image: "{fields.heroImage}"
      - name: categories
        label: Categories
        type: select
        options:
          multiple: true
          fetch:
            url: https://scaffold.draftlab.org/api/categories.json
            results: blog.categories
            value: "{name}"
            label: "{name}"
            

      - name: body
        label: Body
        type: rich-text
